apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime
  labels:
    app: amazon-prime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-prime
  template:
    metadata:
      labels:
        app: amazon-prime
    spec:
      containers:
      - name: amazon-prime
        image: nginx
        ports:
        - containerPort: 80
