apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: amazon-prime
  name: node-exporter
  namespace: prometheus-node-exporter
spec:
  ports:
    - name: node-exporter
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app: node-exporter
  type: NodePort
