apiVersion: v1
kind: Service
metadata:
  labels:
    app: prime-service
    app.kubernetes.io/instance: amazon-prime
  name: prime-service
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: prime-app
  type: LoadBalancer
