apiVersion: v1
kind: Service
metadata:
  name: prime-service
  labels:
    app: prime-service
spec:
  selector:
      app: prime-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
